# Change these first
owner: thatconference # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: THAT.us
    icon: https://that.us/favicon.png
    url: https://that.us/activities
  - name: THATconference.com
    icon: https://www.thatconference.com/favicon.png
    url: https://www.thatconference.com
  - name: THAT API
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    url: $SECRET_SITE
  - name: API Gateway
    # pointed at refresh uri
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    url: $GATEWAY_TEST
    headers:
      - "Content-Type: application/json"
#   - name: API Events
#     url: $EVENTS_TEST
#     headers:
#       - "Content-Type: application/json"
#     body: '{"query":"query{events{all(type:THAT_US){id year slug slogan}}}"}'
#     method: POST
#     __dangerous__body_down: "error"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.that.tech
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ThatConference/that.us/master/public/images/THAT-Full-Wide.svg
  name: THAT Status
  introTitle: "**THAT Status** uptime page of the THAT sites"
  introMessage: This status page which uses **real-time** data from our [Github repository](https://github.com/thatconference/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: THAT.us
      href: https://that.us

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
