# Change these first
owner: thatconference # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: THAT.us
    url: https://that.us/activities
  - name: THAT Conference
    url: https://www.thatconference.com
  - name: THAT API
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.that.tech
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ThatConference/that.us/master/public/images/THAT-Full-Wide.svg
  name: THAT Status
  introTitle: "**THAT Status** uptime status of the THAT sites"
  introMessage: This status page which uses **real-time** data from our [Github repository](https://github.com/thatconference/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
