# Change these first
owner: thatconference # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: THAT.us
    icon: https://that.us/favicon.png
    url: https://that.us/activities
  - name: THATconference.com
    icon: https://www.thatconference.com/favicon.png
    url: https://www.thatconference.com
  - name: API Gateway
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    # pointed at refresh uri
    url: $GATEWAY_TEST
    headers:
      - "Content-Type: application/json"
  - name: API Events
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    url: $EVENTS_TEST
    headers:
      - "Content-Type: application/json"
    __dangerous__body_down: "error"
  - name: API Members
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    url: $MEMBERS_TEST
    headers:
      - "Content-Type: application/json"
    __dangerous__body_down: "error"
  - name: API Partners
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    url: $PARTNERS_TEST
    headers:
      - "Content-Type: application/json"
    __dangerous__body_down: "error"
  - name: API SESSIONS
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    headers:
      - "Content-Type: application/json"
    url: $SESSIONS_TEST
    __dangerous__body_down: "error"
  - name: API GARAGE
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    headers:
      - "Content-Type: application/json"
    url: $GARAGE_TEST
    __dangerous__body_down: "error"
  - name: API COMMUNICATIONS
    icon: https://www.thatconference.com/images/icons/favicon-72.png
    headers:
      - "Content-Type: application/json"
    url: $COMMUNICATIONS_TEST
    __dangerous__body_down: "error"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.that.tech
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/ThatConference/that.us/master/public/images/THAT-Full-Wide.svg
  name: THAT Status
  introTitle: "**THAT Status**"
  introMessage: This status page, for the THAT Sites, uses **real-time** data from our [Status Github repository](https://github.com/thatconference/status). No server required — only GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: THAT.us
      href: https://that.us

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
